update Readme, fields and actions.
membrane-io/membrane-driver-twitter pull request #1
Opened 2023-01-12 00:38 UTC by aranajhonny

@juancampa review this please.

2023-01-12 02:19 UTC, juancampa commented on README.md
> +An [Membrane.io](https://membrane.io/) driver for Twitter.
```suggestion
A [Membrane.io](https://membrane.io/) driver for Twitter.
```

2023-01-12 02:19 UTC, juancampa commented on README.md
> +  ```> Membrame: Update current program```
We can remove this entire part as it's going to be outdated pretty soon and it's understood that you need to be using Membrane to use this driver

2023-01-12 02:19 UTC, juancampa commented on README.md
> +Create a tweet (also support for polls)
```suggestion
Create a tweet (it also support polls!)
```

2023-01-12 02:19 UTC, juancampa commented on README.md
> +$~~~~$`mctl action "twitter:tweet(text: 'Hi!')"`
```suggestion
$~~~~$`mctl action "twitter:tweet(text:'Hi!')"`
```
Currently grefs can't have whitespace. We can fix that later but let's remove all whitespace for now

2023-01-16 22:41 UTC, juancampa requested changes

2023-01-16 22:41 UTC, juancampa commented on util.ts
> +    }, {} as Record<string, string>);
```suggestion
export const parseQS = (qs: string): Record<string, string> =>
  Object.fromEntries(new URLSearchParams(qs).entries())
```

Something like this should work

2023-01-16 22:41 UTC, juancampa commented on util.ts
> -  }
Any reason to remove this? It's good to see this error when a user forgets to invoke `configure`

2023-01-16 22:41 UTC, juancampa commented on README.md
> +## Actions
```suggestion
## Setup
```

2023-01-16 22:41 UTC, juancampa commented on README.md
> +$~~~~$`mctl action "twitter:tweet(text:'Hi!')"`
It would be nice to separate this into two examples `Create a tweet` and `Create a poll tweet`

2023-02-07 07:35 UTC, aranajhonny commented
@juancampa

2023-02-16 15:58 UTC, juancampa approved these changes

2023-02-16 15:58 UTC, merged